// ── DEFAULT PRICING (source of truth) ─────────────────────────
// App.jsx loads from Supabase and falls back to these defaults.
// AdminPanel saves overrides to Supabase.

export const DEFAULT_PRICING = {
  woodwork: [
    { name: "Base Cabinet", price: 190, finLF: 1 },
    { name: "Bench (Open)", price: 130, finLF: 1 },
    { name: "Commercial Cabinet Lower", price: 250, finLF: 0 },
    { name: "Commercial Cabinet Upper", price: 135, finLF: 0 },
    { name: "Flat Veneer End", price: 0, finLF: 0.5 },
    { name: "Fridge End Panels", price: 200, finLF: 2 },
    { name: "Kitchen Hd (Incl in Cab as well)", price: 190, finLF: 2 },
    { name: "Lockers (Open)", price: 160, finLF: 1 },
    { name: "Mantle - Simple LF", price: 110, finLF: 1 },
    { name: "Mantle - Surround", price: 400, finLF: 1 },
    { name: "Paneled Backs/Ends (LF)", price: 100, finLF: 0.75 },
    { name: "Shiplap Basic (Sq Feet)", price: 25, finLF: 1 },
    { name: "Stacked Upper Cabinet", price: 285, finLF: 2 },
    { name: "Tall Cabinet (up to 8ft)", price: 380, finLF: 2.5 },
    { name: "Tall Cabinet (8ft-10ft)", price: 500, finLF: 3 },
    { name: "Upper Cabinet", price: 190, finLF: 1 },
    { name: "Wood Floating Shelves", price: 100, finLF: 0.5 },
    { name: "Millwork (per LF)", price: 1, finLF: 1 },
  ],
  countertops: [
    { name: "Countertop Laminate (Allowance)", price: 75 },
    { name: "Countertop Quartz (Allowance)", price: 250 },
    { name: "Granite / Ln Ft (Allowance)", price: 300 },
    { name: "Wood Tops LF", price: 100 },
  ],
  construction: [
    { name: "Not Applicable", premium: 0 },
    { name: "Standard Overlay", premium: 0 },
    { name: "Full Overlay", premium: 0.05 },
    { name: "Inset", premium: 0.2 },
    { name: "Euro", premium: 0.2 },
    { name: "Furniture Style", premium: 0.65 },
    { name: "Laminate", premium: 0 },
  ],
  wood: [
    { name: "Not Applicable", premium: 0 },
    { name: "Alder", premium: 0.15 },
    { name: "Cherry", premium: 0.15 },
    { name: "Knotty Alder", premium: 0.05 },
    { name: "Laminate", premium: 0 },
    { name: "Maple", premium: 0.15 },
    { name: "Paint Grade", premium: 0 },
    { name: "Red Oak", premium: 0.05 },
    { name: "Rift White Oak", premium: 0.4 },
    { name: "Walnut", premium: 0.4 },
    { name: "White Oak", premium: 0.3 },
  ],
  finishing: [
    { name: "No Finishing", pricePerLF: 0 },
    { name: "Stain", pricePerLF: 90 },
    { name: "Paint", pricePerLF: 90 },
    { name: "Clear Coat", pricePerLF: 65 },
    { name: "Specialty", pricePerLF: 100 },
  ],
  productType: [
    { name: "Cabinets", pricePerLF: 195 },
    { name: "Countertops", pricePerLF: 80 },
    { name: "Mantels", pricePerLF: 100 },
    { name: "Kitchen Hood", pricePerLF: null },
  ],
  installType: [
    { name: "No Install", rate: 0 },
    { name: "Standard or Full Overlay - Unfinished", rate: 0.18 },
    { name: "Standard or Full Overlay - Finished", rate: 0.2 },
    { name: "Inset - Unfinished", rate: 0.2 },
    { name: "Inset - Finished", rate: 0.22 },
    { name: "Euro - Unfinished", rate: 0.3 },
    { name: "Euro - Finished", rate: 0.3 },
    { name: "Hourly Rate", rate: 135 },
  ],
  upgrades: [
    { name: "Closet Rods (Per foot)", price: 25 },
    { name: "Docking Drawer", price: 500 },
    { name: "Dovetail Box Upgrade", price: 50 },
    { name: "Extra Drawers (1- Incl. Non Dovetail)", price: 80 },
    { name: "Farm Sink Fitting Charge", price: 200 },
    { name: "File Drawer", price: 45 },
    { name: "Floating Shelf Brackets (1 pair)", price: 200 },
    { name: "Furniture Style Upgrade", price: 250 },
    { name: "Glass Doors", price: 100 },
    { name: "Glass Shelves", price: 100 },
    { name: "Hanging Rod (Per foot)", price: 25 },
    { name: "Hardware Install (per unit)", price: 12 },
    { name: "Hookstrip (Per foot)", price: 30 },
    { name: "In-Wall Vanity Heavy Duty Bracket (single)", price: 200 },
    { name: "Island Post", price: 275 },
    { name: "Ladder Support (per ft standard wood)", price: 100 },
    { name: "Lazy Susan", price: 475 },
    { name: "Mirrors (Per foot)", price: 50 },
    { name: "Murphy Bed (Twin)", price: 4000 },
    { name: "Notched Dovetail Drawers", price: 200 },
    { name: "Oversized Drawer", price: 150 },
    { name: "Pantry Pullouts", price: 1400 },
    { name: "Peg Drawer", price: 250 },
    { name: "Pocket Doors (Pair)", price: 1000 },
    { name: "Pullout Base Unit (Spice or Utensil Holders)", price: 500 },
    { name: "Raised Panel Door or Appl. Molding (Per opening)", price: 50 },
    { name: "Rollouts (Dovetail - Sidemount Guides)", price: 225 },
    { name: "Rollouts (Melamine - Sidemount Slides)", price: 150 },
    { name: "S. Close Drawer Slides (2) (upgrade)", price: 80 },
    { name: "Sink Tip Out", price: 75 },
    { name: "Specialty Drawer Inserts", price: 215 },
    { name: "Spice Rack (Small Door Rack)", price: 140 },
    { name: "Touch Latch Doors (ea)", price: 25 },
    { name: "Touch Latch Drawers (ea)", price: 250 },
    { name: "Trash Pull Out", price: 450 },
    { name: "Tray Dividers (each)", price: 45 },
    { name: "Trip Charge", price: 200 },
    { name: "Wine Rack", price: 175 },
  ],
}
